import './globals.css'
import { Inter } from 'next/font/google'
import Providers from './providers'
import { classNames } from '@/components/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Providers>
    <html className='bg-gray-950' lang="en">
      <body className={classNames(inter.className, 'h-full')}>{children}</body>
    </html>
    </Providers>
  )
}
